//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimerCounterLister.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimerCounterLister.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_view_list {
            get {
                object obj = ResourceManager.GetObject("application_view_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_rotate_clockwise {
            get {
                object obj = ResourceManager.GetObject("arrow_rotate_clockwise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to withdraw from balance.
        /// </summary>
        internal static string Balance_Details0 {
            get {
                return ResourceManager.GetString("Balance_Details0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total remains in balance..
        /// </summary>
        internal static string Balance_Details1 {
            get {
                return ResourceManager.GetString("Balance_Details1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added to the balance.
        /// </summary>
        internal static string Balance_Details2 {
            get {
                return ResourceManager.GetString("Balance_Details2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the new balance..
        /// </summary>
        internal static string Balance_Details3 {
            get {
                return ResourceManager.GetString("Balance_Details3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transaction detected in for the balance..
        /// </summary>
        internal static string Balance_Details4 {
            get {
                return ResourceManager.GetString("Balance_Details4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Don&apos;t Save.
        /// </summary>
        internal static string Button_DontSave {
            get {
                return ResourceManager.GetString("Button_DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Timer Counter Alarm.
        /// </summary>
        internal static string CMI_Name_AddTimerCounterAlarm {
            get {
                return ResourceManager.GetString("CMI_Name_AddTimerCounterAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Donate.
        /// </summary>
        internal static string CMI_Name_Donate {
            get {
                return ResourceManager.GetString("CMI_Name_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit Profile Details.
        /// </summary>
        internal static string CMI_Name_EditProfileDetails {
            get {
                return ResourceManager.GetString("CMI_Name_EditProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Timer Counter Events Into Excel File.
        /// </summary>
        internal static string CMI_Name_ExportTimerCounterEventsExcel {
            get {
                return ResourceManager.GetString("CMI_Name_ExportTimerCounterEventsExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Timer Counter Events Into Text File.
        /// </summary>
        internal static string CMI_Name_ExportTimerCounterEventsText {
            get {
                return ResourceManager.GetString("CMI_Name_ExportTimerCounterEventsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Profile.
        /// </summary>
        internal static string CMI_Name_NewProfile {
            get {
                return ResourceManager.GetString("CMI_Name_NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New &amp;Timer Counter.
        /// </summary>
        internal static string CMI_Name_NewTimerCounter {
            get {
                return ResourceManager.GetString("CMI_Name_NewTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Profile.
        /// </summary>
        internal static string CMI_Name_OpenProfile {
            get {
                return ResourceManager.GetString("CMI_Name_OpenProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause all Timer Counters.
        /// </summary>
        internal static string CMI_Name_PauseAllTimerCounters {
            get {
                return ResourceManager.GetString("CMI_Name_PauseAllTimerCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Timer Counter.
        /// </summary>
        internal static string CMI_Name_PauseTimerCounter {
            get {
                return ResourceManager.GetString("CMI_Name_PauseTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove Selected Timer Counter.
        /// </summary>
        internal static string CMI_Name_RemoveSelectedTimerCounter {
            get {
                return ResourceManager.GetString("CMI_Name_RemoveSelectedTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Timer Counter Alarm.
        /// </summary>
        internal static string CMI_Name_RemoveTimerCounterAlarm {
            get {
                return ResourceManager.GetString("CMI_Name_RemoveTimerCounterAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Selected Timer Counter Alarm.
        /// </summary>
        internal static string CMI_Name_ResetTimerCounterAlarm {
            get {
                return ResourceManager.GetString("CMI_Name_ResetTimerCounterAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Selected Timer Counter Add Passed Time.
        /// </summary>
        internal static string CMI_Name_ResumeTimerCounterWithDifference {
            get {
                return ResourceManager.GetString("CMI_Name_ResumeTimerCounterWithDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Profile Changes.
        /// </summary>
        internal static string CMI_Name_SaveProfile {
            get {
                return ResourceManager.GetString("CMI_Name_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Profile As.
        /// </summary>
        internal static string CMI_Name_SaveProfileAs {
            get {
                return ResourceManager.GetString("CMI_Name_SaveProfileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About Timer Counter Lister.
        /// </summary>
        internal static string CMI_Name_ShowAbout {
            get {
                return ResourceManager.GetString("CMI_Name_ShowAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website (github).
        /// </summary>
        internal static string CMI_Name_ShowWebsite {
            get {
                return ResourceManager.GetString("CMI_Name_ShowWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki (online help).
        /// </summary>
        internal static string CMI_Name_ShowWiki {
            get {
                return ResourceManager.GetString("CMI_Name_ShowWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Resume all Timer Counters.
        /// </summary>
        internal static string CMI_Name_StartResumeAllTimerCounters {
            get {
                return ResourceManager.GetString("CMI_Name_StartResumeAllTimerCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Resume Selected Timer Counter.
        /// </summary>
        internal static string CMI_Name_StartResumeTimerCounter {
            get {
                return ResourceManager.GetString("CMI_Name_StartResumeTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Transaction.
        /// </summary>
        internal static string CMI_Name_TimerCounterBalanceTransaction {
            get {
                return ResourceManager.GetString("CMI_Name_TimerCounterBalanceTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Counter &amp;Pay.
        /// </summary>
        internal static string CMI_Name_TimerCounterPay {
            get {
                return ResourceManager.GetString("CMI_Name_TimerCounterPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Timer Counter Alarm into selected Timer Counter..
        /// </summary>
        internal static string CMI_Tooltip_AddTimerCounterAlarm {
            get {
                return ResourceManager.GetString("CMI_Tooltip_AddTimerCounterAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation now can be done using PayPal - The safer, easier way to pay online!.
        /// </summary>
        internal static string CMI_Tooltip_Donate {
            get {
                return ResourceManager.GetString("CMI_Tooltip_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current profile details such as name, password and password settings ...etc.
        /// </summary>
        internal static string CMI_Tooltip_EditProfileDetails {
            get {
                return ResourceManager.GetString("CMI_Tooltip_EditProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export selected Timer Counter Events into Excel file..
        /// </summary>
        internal static string CMI_Tooltip_ExportTimerCounterEventsExcel {
            get {
                return ResourceManager.GetString("CMI_Tooltip_ExportTimerCounterEventsExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export selected Timer Counter Events Into a Text file..
        /// </summary>
        internal static string CMI_Tooltip_ExportTimerCounterEventsText {
            get {
                return ResourceManager.GetString("CMI_Tooltip_ExportTimerCounterEventsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new profile which will hold all timers and data related. This will ask to confirm saving changes first..
        /// </summary>
        internal static string CMI_Tooltip_NewProfile {
            get {
                return ResourceManager.GetString("CMI_Tooltip_NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new timer counter to current profile. This will show a dialog allows to enter new counter details..
        /// </summary>
        internal static string CMI_Tooltip_NewTimerCounter {
            get {
                return ResourceManager.GetString("CMI_Tooltip_NewTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open profile from file. This will ask to confirm saving changes first..
        /// </summary>
        internal static string CMI_Tooltip_OpenProfile {
            get {
                return ResourceManager.GetString("CMI_Tooltip_OpenProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause all Timer Counters that currently running..
        /// </summary>
        internal static string CMI_Tooltip_PauseAllTimerCounters {
            get {
                return ResourceManager.GetString("CMI_Tooltip_PauseAllTimerCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause selected Timer Counter. This will ask for a password if the profile is protected by one..
        /// </summary>
        internal static string CMI_Tooltip_PauseTimerCounter {
            get {
                return ResourceManager.GetString("CMI_Tooltip_PauseTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected Timer Counter from the list. This cannot be UNDONE, also, all timer details will be removed, but still, profile will not be saved..
        /// </summary>
        internal static string CMI_Tooltip_RemoveSelectedTimerCounter {
            get {
                return ResourceManager.GetString("CMI_Tooltip_RemoveSelectedTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected Timer Counter Alarm from selected Timer Counter..
        /// </summary>
        internal static string CMI_Tooltip_RemoveTimerCounterAlarm {
            get {
                return ResourceManager.GetString("CMI_Tooltip_RemoveTimerCounterAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset selected Timer Counter Alarm so it count down again from it&apos;s time..
        /// </summary>
        internal static string CMI_Tooltip_ResetTimerCounterAlarm {
            get {
                return ResourceManager.GetString("CMI_Tooltip_ResetTimerCounterAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume selected Timer Counter, add the time has passed from last pause..
        /// </summary>
        internal static string CMI_Tooltip_ResumeTimerCounterWithDifference {
            get {
                return ResourceManager.GetString("CMI_Tooltip_ResumeTimerCounterWithDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all profile changes..
        /// </summary>
        internal static string CMI_Tooltip_SaveProfile {
            get {
                return ResourceManager.GetString("CMI_Tooltip_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current profile into a file and set that file as current..
        /// </summary>
        internal static string CMI_Tooltip_SaveProfileAs {
            get {
                return ResourceManager.GetString("CMI_Tooltip_SaveProfileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open about box with details about the program..
        /// </summary>
        internal static string CMI_Tooltip_ShowAbout {
            get {
                return ResourceManager.GetString("CMI_Tooltip_ShowAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to program&apos;s repository: https://github.com/jegqamas/Timer-Counter-Lister/.
        /// </summary>
        internal static string CMI_Tooltip_ShowWebsite {
            get {
                return ResourceManager.GetString("CMI_Tooltip_ShowWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to program&apos;s wiki page for latest help: https://github.com/jegqamas/Timer-Counter-Lister/wiki.
        /// </summary>
        internal static string CMI_Tooltip_ShowWiki {
            get {
                return ResourceManager.GetString("CMI_Tooltip_ShowWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start or Resume all Timer Counters in the profile..
        /// </summary>
        internal static string CMI_Tooltip_StartResumeAllTimerCounters {
            get {
                return ResourceManager.GetString("CMI_Tooltip_StartResumeAllTimerCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Resume selected Timer Counter. This will ask for a password if the profile is protected by one..
        /// </summary>
        internal static string CMI_Tooltip_StartResumeTimerCounter {
            get {
                return ResourceManager.GetString("CMI_Tooltip_StartResumeTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a Balance Transaction such as Withdraw from Balance or Add to Balance..
        /// </summary>
        internal static string CMI_Tooltip_TimerCounterBalanceTransaction {
            get {
                return ResourceManager.GetString("CMI_Tooltip_TimerCounterBalanceTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berform a pay operation to sort out cost so far to selected Timer Counter..
        /// </summary>
        internal static string CMI_Tooltip_TimerCounterPay {
            get {
                return ResourceManager.GetString("CMI_Tooltip_TimerCounterPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comment {
            get {
                object obj = ResourceManager.GetObject("comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comment_add {
            get {
                object obj = ResourceManager.GetObject("comment_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comment_delete {
            get {
                object obj = ResourceManager.GetObject("comment_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comment_edit {
            get {
                object obj = ResourceManager.GetObject("comment_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comments {
            get {
                object obj = ResourceManager.GetObject("comments", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comments_add {
            get {
                object obj = ResourceManager.GetObject("comments_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comments_delete {
            get {
                object obj = ResourceManager.GetObject("comments_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control_pause {
            get {
                object obj = ResourceManager.GetObject("control_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control_pause_blue {
            get {
                object obj = ResourceManager.GetObject("control_pause_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control_play {
            get {
                object obj = ResourceManager.GetObject("control_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control_play_blue {
            get {
                object obj = ResourceManager.GetObject("control_play_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control_stop {
            get {
                object obj = ResourceManager.GetObject("control_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control_stop_blue {
            get {
                object obj = ResourceManager.GetObject("control_stop_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Recent Profiles.
        /// </summary>
        internal static string DMI_Name_RecentProfiles {
            get {
                return ResourceManager.GetString("DMI_Name_RecentProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap door_in {
            get {
                object obj = ResourceManager.GetObject("door_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add new Timer Counter: incorrect password..
        /// </summary>
        internal static string Error_CannotAddNewTimerCounterIncorrectPassword {
            get {
                return ResourceManager.GetString("Error_CannotAddNewTimerCounterIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add new Timer Counter: incorrect profile password..
        /// </summary>
        internal static string Error_CannotAddNewTimerIncorrectPassword {
            get {
                return ResourceManager.GetString("Error_CannotAddNewTimerIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot do Balance Transaction: incorrect password..
        /// </summary>
        internal static string Error_CannotDoTimerCounterBalanceTransactionIncorrectPassword {
            get {
                return ResourceManager.GetString("Error_CannotDoTimerCounterBalanceTransactionIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit profile details, incorrect password..
        /// </summary>
        internal static string Error_CannotEditProfileDetailsIncorrectPassword {
            get {
                return ResourceManager.GetString("Error_CannotEditProfileDetailsIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open profile: incorrect password entered !!.
        /// </summary>
        internal static string Error_CannotOpenProfileIncorrectPassword {
            get {
                return ResourceManager.GetString("Error_CannotOpenProfileIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open profile: path is null or empty..
        /// </summary>
        internal static string Error_CannotOpenProfilePathIsEmpty {
            get {
                return ResourceManager.GetString("Error_CannotOpenProfilePathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open profile: path does not exist..
        /// </summary>
        internal static string Error_CannotOpenProfilePathNotExist {
            get {
                return ResourceManager.GetString("Error_CannotOpenProfilePathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pause selected Timer Counter: incorrect password..
        /// </summary>
        internal static string Error_CannotPauseTimerCounterIncorrectPassword {
            get {
                return ResourceManager.GetString("Error_CannotPauseTimerCounterIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove selected Timer Counter: incorrect password..
        /// </summary>
        internal static string Error_CannotRemoveSelectedTimerCounterIncorrectPassword {
            get {
                return ResourceManager.GetString("Error_CannotRemoveSelectedTimerCounterIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save profile: profile is protected with a password and incorrect password has been entered..
        /// </summary>
        internal static string Error_CannotSaveProfileIncorrectPassword {
            get {
                return ResourceManager.GetString("Error_CannotSaveProfileIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save profile: saving profile has been canceled internally..
        /// </summary>
        internal static string Error_CannotSaveProfileItHasCanceledInternally {
            get {
                return ResourceManager.GetString("Error_CannotSaveProfileItHasCanceledInternally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add Timer Counter Alarm: incorrect password..
        /// </summary>
        internal static string Error_CannotTimerCounteralarmAddIncorrectPassword {
            get {
                return ResourceManager.GetString("Error_CannotTimerCounteralarmAddIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove Timer Counter Alarm: incorrect password !!.
        /// </summary>
        internal static string Error_CannotTimerCounterAlarmRemoveIncorrectPassword {
            get {
                return ResourceManager.GetString("Error_CannotTimerCounterAlarmRemoveIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot do pay operation to Selected Counter: incorrect password..
        /// </summary>
        internal static string Error_CannotTimerCounterPayIncorrectPassword {
            get {
                return ResourceManager.GetString("Error_CannotTimerCounterPayIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not Timer Counter Lister file.
        /// </summary>
        internal static string Error_FileIsNotTCLFile {
            get {
                return ResourceManager.GetString("Error_FileIsNotTCLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size is less than expected.
        /// </summary>
        internal static string Error_FileSizeIsLessThanExpected {
            get {
                return ResourceManager.GetString("Error_FileSizeIsLessThanExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible Timer Counter Lister file version.
        /// </summary>
        internal static string Error_InomplatibleTCLFileVersion {
            get {
                return ResourceManager.GetString("Error_InomplatibleTCLFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible Timer Counter Lister profile version.
        /// </summary>
        internal static string Error_InomplatibleTCLProfileVersion {
            get {
                return ResourceManager.GetString("Error_InomplatibleTCLProfileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile start has been canceled.
        /// </summary>
        internal static string Error_NewProfileStartCanceled {
            get {
                return ResourceManager.GetString("Error_NewProfileStartCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open profile: open profile has been canceled..
        /// </summary>
        internal static string Error_OpenProfileCanceled {
            get {
                return ResourceManager.GetString("Error_OpenProfileCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save profile has been canceled..
        /// </summary>
        internal static string Error_SaveProfileCanceled {
            get {
                return ResourceManager.GetString("Error_SaveProfileCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving method is set to none..
        /// </summary>
        internal static string Error_SavingMethodSetToNone {
            get {
                return ResourceManager.GetString("Error_SavingMethodSetToNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open profile file.
        /// </summary>
        internal static string Error_UnableToOpenProfileFile {
            get {
                return ResourceManager.GetString("Error_UnableToOpenProfileFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open profile: unkown error. Please check out files (if any) in the Exceptions folder in &quot;Documents\Timer Counter Lister&quot; folder for more details..
        /// </summary>
        internal static string Error_UnableToOpenProfileUnknownReason {
            get {
                return ResourceManager.GetString("Error_UnableToOpenProfileUnknownReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save profile.
        /// </summary>
        internal static string Error_UnableToSaveProfile {
            get {
                return ResourceManager.GetString("Error_UnableToSaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap film {
            get {
                object obj = ResourceManager.GetObject("film", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap film_edit {
            get {
                object obj = ResourceManager.GetObject("film_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Counter Lister Profile (*.tclp)|*.tclp.
        /// </summary>
        internal static string Filter_TCLP {
            get {
                return ResourceManager.GetString("Filter_TCLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File (*.txt)|*.txt.
        /// </summary>
        internal static string Filter_Text {
            get {
                return ResourceManager.GetString("Filter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALARM TRIGGER !!.
        /// </summary>
        internal static string Message_AlarmTrigger {
            get {
                return ResourceManager.GetString("Message_AlarmTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove selected Timer Counter ? THIS CAN NOT BE UNDONE..
        /// </summary>
        internal static string Message_AreYouSureToRemoveTimerCounter {
            get {
                return ResourceManager.GetString("Message_AreYouSureToRemoveTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close the application, profile is password protected and incorrect password has been entered..
        /// </summary>
        internal static string Message_CannotCloseAppProfileIsPasswordProtectedWrongPassworf {
            get {
                return ResourceManager.GetString("Message_CannotCloseAppProfileIsPasswordProtectedWrongPassworf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close the application, profile is not saved..
        /// </summary>
        internal static string Message_CannotCloseAppProfileNotSaved {
            get {
                return ResourceManager.GetString("Message_CannotCloseAppProfileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a Timer Counter or more still running. Application cannot closed until these timers are halted or paused..
        /// </summary>
        internal static string Message_CannotCloseAppTimersStillRunning {
            get {
                return ResourceManager.GetString("Message_CannotCloseAppTimersStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove Timer Counter Alarm: please select the Alarm to remove first !!.
        /// </summary>
        internal static string Message_CannotRemoveAlarmPleaseSelectAlarm {
            get {
                return ResourceManager.GetString("Message_CannotRemoveAlarmPleaseSelectAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reset Timer Counter Alarm: please select a Timer Counter Alarm first..
        /// </summary>
        internal static string Message_CannotResetAlarmPleaseSelectAlarm {
            get {
                return ResourceManager.GetString("Message_CannotResetAlarmPleaseSelectAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature cannot be used with this Timer Counter (Resume Timer Counter With Difference Add is not allowed)..
        /// </summary>
        internal static string Message_CannotResumeWithAddNotAllowed {
            get {
                return ResourceManager.GetString("Message_CannotResumeWithAddNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save profile changes first ?.
        /// </summary>
        internal static string Message_DoYouWantToSaveProfileFirst {
            get {
                return ResourceManager.GetString("Message_DoYouWantToSaveProfileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered name is already taken by another Timer Counter. Please enter a different name..
        /// </summary>
        internal static string Message_EnteredNameAlreadyTakenByAnotherTimer {
            get {
                return ResourceManager.GetString("Message_EnteredNameAlreadyTakenByAnotherTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Timer Counter Alarm is arelady taken ba another one. Please enter a different Alarm name..
        /// </summary>
        internal static string Message_EnteredNameAlreadyTakenByAnotherTimerAlarm {
            get {
                return ResourceManager.GetString("Message_EnteredNameAlreadyTakenByAnotherTimerAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password !!.
        /// </summary>
        internal static string Message_IncorrectPassword {
            get {
                return ResourceManager.GetString("Message_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profile is loaded ! please start a new profile or open a saved one..
        /// </summary>
        internal static string Message_NoProfileLoaded {
            get {
                return ResourceManager.GetString("Message_NoProfileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Timer Counter in current profile !!.
        /// </summary>
        internal static string Message_NoTimerCounterInProfile {
            get {
                return ResourceManager.GetString("Message_NoTimerCounterInProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully..
        /// </summary>
        internal static string Message_PasswordHasBeenChangedSuccessfully {
            get {
                return ResourceManager.GetString("Message_PasswordHasBeenChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter currency first..
        /// </summary>
        internal static string Message_PleaseEnterCurrencyFirst {
            get {
                return ResourceManager.GetString("Message_PleaseEnterCurrencyFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter profile name first !!.
        /// </summary>
        internal static string Message_PleaseEnterProfileNameFirst {
            get {
                return ResourceManager.GetString("Message_PleaseEnterProfileNameFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter profile password first, or uncheck &quot;Protect profile with a password&quot;..
        /// </summary>
        internal static string Message_PleaseEnterProfilePasswordFirst {
            get {
                return ResourceManager.GetString("Message_PleaseEnterProfilePasswordFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter (or set) profile file path first..
        /// </summary>
        internal static string Message_PleaseEnterProfilePathFirst {
            get {
                return ResourceManager.GetString("Message_PleaseEnterProfilePathFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Timer Counter name first..
        /// </summary>
        internal static string Message_PleaseEnterTimerCounterAlarmNameFirst {
            get {
                return ResourceManager.GetString("Message_PleaseEnterTimerCounterAlarmNameFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Timer Counter Alarm time (it must be larger than zero)..
        /// </summary>
        internal static string Message_PleaseEnterTimerCounterAlarmTime {
            get {
                return ResourceManager.GetString("Message_PleaseEnterTimerCounterAlarmTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter timer counter name first..
        /// </summary>
        internal static string Message_PleaseEnterTimerCounterNameFirst {
            get {
                return ResourceManager.GetString("Message_PleaseEnterTimerCounterNameFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Timer Counter first..
        /// </summary>
        internal static string Message_PleaseSelectTimerCounter {
            get {
                return ResourceManager.GetString("Message_PleaseSelectTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Timer Counter is already paused !!.
        /// </summary>
        internal static string Message_SelectedTimerCounterAlreadyPaused {
            get {
                return ResourceManager.GetString("Message_SelectedTimerCounterAlreadyPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Timer Counter is already running !!.
        /// </summary>
        internal static string Message_SelectedTimerCounterAlreadyRunning {
            get {
                return ResourceManager.GetString("Message_SelectedTimerCounterAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Timer Counter need to be paused first !!.
        /// </summary>
        internal static string Message_TimerCounterNeedToBePausedFirst {
            get {
                return ResourceManager.GetString("Message_TimerCounterNeedToBePausedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a Timer Counter or more still running. Cannot start new profile until all timer counters of current profile are halted or paused..
        /// </summary>
        internal static string Message_TimersNeedToPauseToMakeNewProfile {
            get {
                return ResourceManager.GetString("Message_TimersNeedToPauseToMakeNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a Timer Counter or more still running. Cannot open another profile until all timer counters of current profile are halted or paused..
        /// </summary>
        internal static string Message_TimersNeedToPauseToOpenProfile {
            get {
                return ResourceManager.GetString("Message_TimersNeedToPauseToOpenProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password, new password doesn&apos;t match (not confirmed)..
        /// </summary>
        internal static string Message_UnableToChangePasswordNotConfimed {
            get {
                return ResourceManager.GetString("Message_UnableToChangePasswordNotConfimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Timer Counter.
        /// </summary>
        internal static string MessageCaption_AddTimerCounter {
            get {
                return ResourceManager.GetString("MessageCaption_AddTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Timer Counter Alarm.
        /// </summary>
        internal static string MessageCaption_AddTimerCounterAlarm {
            get {
                return ResourceManager.GetString("MessageCaption_AddTimerCounterAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Trigger.
        /// </summary>
        internal static string MessageCaption_AlarmTrigger {
            get {
                return ResourceManager.GetString("MessageCaption_AlarmTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string MessageCaption_ChangePassword {
            get {
                return ResourceManager.GetString("MessageCaption_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Timer Counter.
        /// </summary>
        internal static string MessageCaption_RemoveTimerCounter {
            get {
                return ResourceManager.GetString("MessageCaption_RemoveTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string MessageCaption_SaveChanges {
            get {
                return ResourceManager.GetString("MessageCaption_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Profiles.
        /// </summary>
        internal static string MIR_Name_Profiles {
            get {
                return ResourceManager.GetString("MIR_Name_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Counter Cont&amp;rols.
        /// </summary>
        internal static string MIR_Name_TimerCounterControls {
            get {
                return ResourceManager.GetString("MIR_Name_TimerCounterControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer &amp;Conuters.
        /// </summary>
        internal static string MIR_Name_TimerCounters {
            get {
                return ResourceManager.GetString("MIR_Name_TimerCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money {
            get {
                object obj = ResourceManager.GetObject("money", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money_delete {
            get {
                object obj = ResourceManager.GetObject("money_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white {
            get {
                object obj = ResourceManager.GetObject("page_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_edit {
            get {
                object obj = ResourceManager.GetObject("page_white_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_excel {
            get {
                object obj = ResourceManager.GetObject("page_white_excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payed from balance.
        /// </summary>
        internal static string Pay_Details0 {
            get {
                return ResourceManager.GetString("Pay_Details0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total payed using entering amount.
        /// </summary>
        internal static string Pay_Details1 {
            get {
                return ResourceManager.GetString("Pay_Details1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon properties {
            get {
                object obj = ResourceManager.GetObject("properties", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute command &quot;new profile&quot;: current profile changes aren&apos;t saved..
        /// </summary>
        internal static string Status_CannotExecuteCommandNewProfile0 {
            get {
                return ResourceManager.GetString("Status_CannotExecuteCommandNewProfile0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile started successfully..
        /// </summary>
        internal static string Status_NewProfileStartedSuccessfully {
            get {
                return ResourceManager.GetString("Status_NewProfileStartedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile opened successfully..
        /// </summary>
        internal static string Status_ProfileOpenedSuccessfully {
            get {
                return ResourceManager.GetString("Status_ProfileOpenedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile saved successfully..
        /// </summary>
        internal static string Status_ProfileSavedSuccessfully {
            get {
                return ResourceManager.GetString("Status_ProfileSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting new profile.
        /// </summary>
        internal static string Status_StartingNewProfile {
            get {
                return ResourceManager.GetString("Status_StartingNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table {
            get {
                object obj = ResourceManager.GetObject("table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Counter Alarms.
        /// </summary>
        internal static string TC_Name_Alarms {
            get {
                return ResourceManager.GetString("TC_Name_Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Details.
        /// </summary>
        internal static string TC_Name_ProfileDetails {
            get {
                return ResourceManager.GetString("TC_Name_ProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Counter Events.
        /// </summary>
        internal static string TC_Name_TimerCounterEvents {
            get {
                return ResourceManager.GetString("TC_Name_TimerCounterEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Counters.
        /// </summary>
        internal static string TC_Name_TimerCounters {
            get {
                return ResourceManager.GetString("TC_Name_TimerCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Counter Status.
        /// </summary>
        internal static string TC_Name_TimerCounterStatus {
            get {
                return ResourceManager.GetString("TC_Name_TimerCounterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap time {
            get {
                object obj = ResourceManager.GetObject("time", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap time_add {
            get {
                object obj = ResourceManager.GetObject("time_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap time_delete {
            get {
                object obj = ResourceManager.GetObject("time_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap time_go {
            get {
                object obj = ResourceManager.GetObject("time_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timeline_marker {
            get {
                object obj = ResourceManager.GetObject("timeline_marker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TimerCounterLister {
            get {
                object obj = ResourceManager.GetObject("TimerCounterLister", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events are exported into Excel file.
        /// </summary>
        internal static string TimerDescDesc_ExportEventsIntoExcel {
            get {
                return ResourceManager.GetString("TimerDescDesc_ExportEventsIntoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Add.
        /// </summary>
        internal static string TimerEvent_AlarmAdd {
            get {
                return ResourceManager.GetString("TimerEvent_AlarmAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Remove.
        /// </summary>
        internal static string TimerEvent_AlarmRemove {
            get {
                return ResourceManager.GetString("TimerEvent_AlarmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Reset.
        /// </summary>
        internal static string TimerEvent_AlarmReset {
            get {
                return ResourceManager.GetString("TimerEvent_AlarmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Trigger.
        /// </summary>
        internal static string TimerEvent_AlarmTrigger {
            get {
                return ResourceManager.GetString("TimerEvent_AlarmTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Transaction.
        /// </summary>
        internal static string TimerEvent_BalanceTransaction {
            get {
                return ResourceManager.GetString("TimerEvent_BalanceTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Counter Events Export Into Excel File.
        /// </summary>
        internal static string TimerEvent_ExportEventsIntoExcel {
            get {
                return ResourceManager.GetString("TimerEvent_ExportEventsIntoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Counter Events Export Into Text File.
        /// </summary>
        internal static string TimerEvent_ExportEventsIntoText {
            get {
                return ResourceManager.GetString("TimerEvent_ExportEventsIntoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string TimerEvent_Pay {
            get {
                return ResourceManager.GetString("TimerEvent_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Add.
        /// </summary>
        internal static string TimerEvent_TimerAdd {
            get {
                return ResourceManager.GetString("TimerEvent_TimerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Resume With Difference Add.
        /// </summary>
        internal static string TimerEvent_TimerCounterResumeWithDifference {
            get {
                return ResourceManager.GetString("TimerEvent_TimerCounterResumeWithDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Pause.
        /// </summary>
        internal static string TimerEvent_TimerPause {
            get {
                return ResourceManager.GetString("TimerEvent_TimerPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Resume.
        /// </summary>
        internal static string TimerEvent_TimerResume {
            get {
                return ResourceManager.GetString("TimerEvent_TimerResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Start.
        /// </summary>
        internal static string TimerEvent_TimerStart {
            get {
                return ResourceManager.GetString("TimerEvent_TimerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm removed.
        /// </summary>
        internal static string TimerEventDesc_AlarmRemove {
            get {
                return ResourceManager.GetString("TimerEventDesc_AlarmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm reset.
        /// </summary>
        internal static string TimerEventDesc_AlarmReset {
            get {
                return ResourceManager.GetString("TimerEventDesc_AlarmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events are exported into text file.
        /// </summary>
        internal static string TimerEventDesc_ExportEventsIntoText {
            get {
                return ResourceManager.GetString("TimerEventDesc_ExportEventsIntoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer added into the profile.
        /// </summary>
        internal static string TimerEventDesc_TimerAdd {
            get {
                return ResourceManager.GetString("TimerEventDesc_TimerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm added to trigger after.
        /// </summary>
        internal static string TimerEventDesc_TimerDesc {
            get {
                return ResourceManager.GetString("TimerEventDesc_TimerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer paused..
        /// </summary>
        internal static string TimerEventDesc_TimerPause {
            get {
                return ResourceManager.GetString("TimerEventDesc_TimerPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Counter paused because of alarm trigger (that alarm is set to pause the Timer Counter on trigger).
        /// </summary>
        internal static string TimerEventDesc_TimerPauseBecauseOfTimer {
            get {
                return ResourceManager.GetString("TimerEventDesc_TimerPauseBecauseOfTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer resumed after a pause.
        /// </summary>
        internal static string TimerEventDesc_TimerResume {
            get {
                return ResourceManager.GetString("TimerEventDesc_TimerResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer resume with adding the time difference from last pause of.
        /// </summary>
        internal static string TimerEventDesc_TimerResumeWithDifference {
            get {
                return ResourceManager.GetString("TimerEventDesc_TimerResumeWithDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer started.
        /// </summary>
        internal static string TimerEventDesc_TimerStart {
            get {
                return ResourceManager.GetString("TimerEventDesc_TimerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Profile Password.
        /// </summary>
        internal static string Title_EnterProfilePassword {
            get {
                return ResourceManager.GetString("Title_EnterProfilePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Timer Counter Events Into Text File.
        /// </summary>
        internal static string Title_ExportTimerCounterEventsIntoText {
            get {
                return ResourceManager.GetString("Title_ExportTimerCounterEventsIntoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Profile.
        /// </summary>
        internal static string Title_OpenProfile {
            get {
                return ResourceManager.GetString("Title_OpenProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter CURRENT Password.
        /// </summary>
        internal static string Title_PleaseEnterCURRENTPassword {
            get {
                return ResourceManager.GetString("Title_PleaseEnterCURRENTPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter NEW Password.
        /// </summary>
        internal static string Title_PleaseEnterNEWPassword {
            get {
                return ResourceManager.GetString("Title_PleaseEnterNEWPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter NEW Password Again To Confirm.
        /// </summary>
        internal static string Title_PleaseEnterNEWPasswordAgainToConfirm {
            get {
                return ResourceManager.GetString("Title_PleaseEnterNEWPasswordAgainToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Profile.
        /// </summary>
        internal static string Title_SaveProfile {
            get {
                return ResourceManager.GetString("Title_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Title_Untitled {
            get {
                return ResourceManager.GetString("Title_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Counter Lister
        ///A program that list and manage timers.
        ///
        ///Copyright © Alaa Ibrahim Hadid 2021 - 2022
        ///
        ///This program is built using ManagedUi, An advanced managed enviroment for C# desktop applications.
        ///Please see &lt;https://github.com/jegqamas/Managed-UI&gt; for more details.
        ///
        ///Copying:
        ///-------
        ///This program is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3 of the License, or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Word_AboutDetails {
            get {
                return ResourceManager.GetString("Word_AboutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alaa Ibrahim Hadid.
        /// </summary>
        internal static string Word_AlaaIbrahimHadid {
            get {
                return ResourceManager.GetString("Word_AlaaIbrahimHadid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string Word_Alarm {
            get {
                return ResourceManager.GetString("Word_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Description.
        /// </summary>
        internal static string Word_AlarmDescription {
            get {
                return ResourceManager.GetString("Word_AlarmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Name.
        /// </summary>
        internal static string Word_AlarmName {
            get {
                return ResourceManager.GetString("Word_AlarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance After Event.
        /// </summary>
        internal static string Word_BalanceAfterEvent {
            get {
                return ResourceManager.GetString("Word_BalanceAfterEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Interval (Clock Rate).
        /// </summary>
        internal static string Word_ClockRate {
            get {
                return ResourceManager.GetString("Word_ClockRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Word_Copyright {
            get {
                return ResourceManager.GetString("Word_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
        ///
        ///You should have received a copy  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Word_CopyrightMessage {
            get {
                return ResourceManager.GetString("Word_CopyrightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost After Event.
        /// </summary>
        internal static string Word_CostAfterEvent {
            get {
                return ResourceManager.GetString("Word_CostAfterEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency After Event.
        /// </summary>
        internal static string Word_CurrencyAfterEvent {
            get {
                return ResourceManager.GetString("Word_CurrencyAfterEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Event.
        /// </summary>
        internal static string Word_DateOfEvent {
            get {
                return ResourceManager.GetString("Word_DateOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Word_Days {
            get {
                return ResourceManager.GetString("Word_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Description.
        /// </summary>
        internal static string Word_EventDescription {
            get {
                return ResourceManager.GetString("Word_EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        internal static string Word_EventName {
            get {
                return ResourceManager.GetString("Word_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Word_Events {
            get {
                return ResourceManager.GetString("Word_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Word_Hours {
            get {
                return ResourceManager.GetString("Word_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        internal static string Word_Milliseconds {
            get {
                return ResourceManager.GetString("Word_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Word_Minutes {
            get {
                return ResourceManager.GetString("Word_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Word_No {
            get {
                return ResourceManager.GetString("Word_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Minute.
        /// </summary>
        internal static string Word_PerMinute {
            get {
                return ResourceManager.GetString("Word_PerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Word_Seconds {
            get {
                return ResourceManager.GetString("Word_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Passed.
        /// </summary>
        internal static string Word_TimePassed {
            get {
                return ResourceManager.GetString("Word_TimePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Counter.
        /// </summary>
        internal static string Word_TimerCounter {
            get {
                return ResourceManager.GetString("Word_TimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to triggered.
        /// </summary>
        internal static string Word_Triggered {
            get {
                return ResourceManager.GetString("Word_Triggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Word_Version {
            get {
                return ResourceManager.GetString("Word_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author, developer and programmer.
        /// </summary>
        internal static string Word_WrittenBy {
            get {
                return ResourceManager.GetString("Word_WrittenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Word_Yes {
            get {
                return ResourceManager.GetString("Word_Yes", resourceCulture);
            }
        }
    }
}
