//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimerCounterLister.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentProfiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentProfiles"]));
            }
            set {
                this["RecentProfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte ProfileSavingMethod {
            get {
                return ((byte)(this["ProfileSavingMethod"]));
            }
            set {
                this["ProfileSavingMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProfileUseCompressInSaving {
            get {
                return ((bool)(this["ProfileUseCompressInSaving"]));
            }
            set {
                this["ProfileUseCompressInSaving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TimerIntervalInMilliseconds {
            get {
                return ((int)(this["TimerIntervalInMilliseconds"]));
            }
            set {
                this["TimerIntervalInMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TimerCounterEvents_Column0 {
            get {
                return ((int)(this["TimerCounterEvents_Column0"]));
            }
            set {
                this["TimerCounterEvents_Column0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounterEvents_Column1 {
            get {
                return ((int)(this["TimerCounterEvents_Column1"]));
            }
            set {
                this["TimerCounterEvents_Column1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounterEvents_Column2 {
            get {
                return ((int)(this["TimerCounterEvents_Column2"]));
            }
            set {
                this["TimerCounterEvents_Column2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounterEvents_Column3 {
            get {
                return ((int)(this["TimerCounterEvents_Column3"]));
            }
            set {
                this["TimerCounterEvents_Column3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounterEvents_Column4 {
            get {
                return ((int)(this["TimerCounterEvents_Column4"]));
            }
            set {
                this["TimerCounterEvents_Column4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounterEvents_Column5 {
            get {
                return ((int)(this["TimerCounterEvents_Column5"]));
            }
            set {
                this["TimerCounterEvents_Column5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounterEvents_Column6 {
            get {
                return ((int)(this["TimerCounterEvents_Column6"]));
            }
            set {
                this["TimerCounterEvents_Column6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TimerCounterAlarm_Column0 {
            get {
                return ((int)(this["TimerCounterAlarm_Column0"]));
            }
            set {
                this["TimerCounterAlarm_Column0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounterAlarm_Column1 {
            get {
                return ((int)(this["TimerCounterAlarm_Column1"]));
            }
            set {
                this["TimerCounterAlarm_Column1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounterAlarm_Column2 {
            get {
                return ((int)(this["TimerCounterAlarm_Column2"]));
            }
            set {
                this["TimerCounterAlarm_Column2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounterAlarm_Column3 {
            get {
                return ((int)(this["TimerCounterAlarm_Column3"]));
            }
            set {
                this["TimerCounterAlarm_Column3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounterAlarm_Column4 {
            get {
                return ((int)(this["TimerCounterAlarm_Column4"]));
            }
            set {
                this["TimerCounterAlarm_Column4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounterAlarm_Column5 {
            get {
                return ((int)(this["TimerCounterAlarm_Column5"]));
            }
            set {
                this["TimerCounterAlarm_Column5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TimerCounters_Column0 {
            get {
                return ((int)(this["TimerCounters_Column0"]));
            }
            set {
                this["TimerCounters_Column0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounters_Column1 {
            get {
                return ((int)(this["TimerCounters_Column1"]));
            }
            set {
                this["TimerCounters_Column1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounters_Column2 {
            get {
                return ((int)(this["TimerCounters_Column2"]));
            }
            set {
                this["TimerCounters_Column2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounters_Column3 {
            get {
                return ((int)(this["TimerCounters_Column3"]));
            }
            set {
                this["TimerCounters_Column3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounters_Column4 {
            get {
                return ((int)(this["TimerCounters_Column4"]));
            }
            set {
                this["TimerCounters_Column4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounters_Column5 {
            get {
                return ((int)(this["TimerCounters_Column5"]));
            }
            set {
                this["TimerCounters_Column5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounters_Column6 {
            get {
                return ((int)(this["TimerCounters_Column6"]));
            }
            set {
                this["TimerCounters_Column6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int TimerCounters_Column7 {
            get {
                return ((int)(this["TimerCounters_Column7"]));
            }
            set {
                this["TimerCounters_Column7"] = value;
            }
        }
    }
}
